-- AlterTable SimpleQuery
ALTER TABLE "SimpleQuery" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "SimpleQuery" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'NEW';
ALTER TABLE "SimpleQuery" ADD COLUMN "notes" TEXT;
ALTER TABLE "SimpleQuery" ALTER COLUMN "userId" DROP NOT NULL;
